GET http://localhost:8080/ca1/api/cities

###
GET http://localhost:8080/ca1/api/cities/zip/2800

###
GET http://localhost:8080/ca1/api/cities/

###
GET http://localhost:8080/ca1/api/hobbies/454
Content-Type: application/json


###
POST http://localhost:8080/devops_starter_war_exploded/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}


###
POST http://localhost:8080/ca1/api/persons
Content-Type: application/json

{
  "email": "owais11@mail.com",
  "firstName": "Owais",
  "lastName": "Dut",
  "phone": {
    "number": "50505053",
    "description": "Telmore",
    "isPrivate": false
  },
  "address": {
    "street": "Lego Blv",
    "additionalInfo": "3th",
    "isPrivate": false,
    "cityInfo": {
      "zipCode": 2800
    }
  }
}

###
GET http://localhost:8080/ca1/api/persons/6/addhobby/454
Content-Type: application/json

###
PUT http://localhost:8080/ca1/api/persons/5
Content-Type: application/json

{"email": "elon@gmail.gov",
"firstName": "Elon",
"lastName":  "Musk"}

###
DELETE http://localhost:8080/ca1/api/persons/21
