INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0555','Scanning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0800','Høje Taastrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0877','København C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0892','Sjælland USF P');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0893','Sjælland USF B');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0894','Udbetaling');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0897','eBrevsprækken');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0899','Kommuneservice');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0900','København C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0910','København C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0917','Københavns Pakkecenter');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0918','Københavns Pakke BRC');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0919','Returprint BRC');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0929','København C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0960','Internationalt Postcenter');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('0999','København C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1000','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1001','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1002','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1003','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1004','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1005','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1006','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1007','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1008','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1009','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1010','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1011','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1012','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1013','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1014','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1015','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1016','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1017','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1018','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1019','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1020','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1021','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1022','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1023','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1024','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1025','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1026','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1045','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1050','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1051','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1052','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1053','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1054','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1055','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1056','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1057','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1058','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1059','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1060','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1061','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1062','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1063','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1064','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1065','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1066','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1067','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1068','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1069','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1070','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1071','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1072','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1073','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1074','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1092','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1093','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1095','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1098','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1100','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1101','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1102','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1103','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1104','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1105','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1106','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1107','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1110','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1111','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1112','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1113','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1114','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1115','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1116','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1117','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1118','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1119','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1120','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1121','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1122','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1123','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1124','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1125','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1126','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1127','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1128','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1129','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1130','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1131','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1140','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1147','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1148','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1150','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1151','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1152','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1153','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1154','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1155','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1156','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1157','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1158','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1159','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1160','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1161','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1162','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1163','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1164','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1165','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1166','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1167','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1168','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1169','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1170','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1171','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1172','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1173','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1174','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1175','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1200','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1201','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1202','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1203','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1204','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1205','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1206','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1207','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1208','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1209','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1210','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1211','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1212','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1213','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1214','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1215','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1216','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1217','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1218','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1219','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1220','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1221','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1240','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1250','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1251','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1252','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1253','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1254','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1255','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1256','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1257','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1258','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1259','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1260','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1261','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1263','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1264','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1265','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1266','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1267','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1268','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1270','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1271','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1291','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1300','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1301','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1302','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1303','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1304','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1306','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1307','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1308','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1309','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1310','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1311','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1312','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1313','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1314','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1315','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1316','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1317','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1318','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1319','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1320','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1321','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1322','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1323','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1324','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1325','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1326','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1327','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1328','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1329','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1350','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1352','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1353','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1354','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1355','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1356','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1357','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1358','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1359','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1360','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1361','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1362','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1363','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1364','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1365','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1366','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1367','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1368','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1369','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1370','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1371','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1400','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1401','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1402','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1403','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1404','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1406','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1407','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1408','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1409','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1410','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1411','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1412','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1413','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1414','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1415','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1416','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1417','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1418','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1419','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1420','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1421','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1422','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1423','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1424','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1425','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1426','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1427','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1428','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1429','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1430','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1431','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1432','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1433','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1434','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1435','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1436','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1437','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1438','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1439','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1440','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1441','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1448','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1450','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1452','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1453','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1454','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1455','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1456','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1457','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1458','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1459','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1460','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1461','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1462','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1463','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1464','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1465','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1466','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1467','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1468','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1470','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1471','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1472','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1473','København K');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1500','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1501','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1502','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1503','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1504','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1505','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1506','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1507','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1508','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1509','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1510','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1512','Returpost');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1513','Centraltastning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1532','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1533','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1550','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1551','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1552','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1553','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1554','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1555','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1556','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1557','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1558','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1559','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1560','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1561','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1562','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1563','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1564','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1566','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1567','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1568','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1569','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1570','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1571','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1572','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1573','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1574','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1575','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1576','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1577','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1592','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1599','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1600','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1601','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1602','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1603','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1604','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1605','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1606','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1607','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1608','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1609','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1610','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1611','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1612','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1613','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1614','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1615','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1616','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1617','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1618','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1619','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1620','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1621','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1622','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1623','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1624','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1630','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1631','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1632','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1633','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1634','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1635','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1650','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1651','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1652','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1653','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1654','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1655','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1656','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1657','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1658','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1659','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1660','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1661','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1662','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1663','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1664','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1665','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1666','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1667','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1668','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1669','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1670','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1671','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1672','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1673','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1674','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1675','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1676','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1677','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1699','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1700','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1701','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1702','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1703','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1704','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1705','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1706','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1707','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1708','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1709','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1710','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1711','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1712','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1713','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1714','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1715','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1716','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1717','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1718','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1719','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1720','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1721','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1722','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1723','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1724','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1725','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1726','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1727','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1728','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1729','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1730','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1731','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1732','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1733','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1734','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1735','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1736','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1737','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1738','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1739','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1749','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1750','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1751','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1752','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1753','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1754','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1755','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1756','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1757','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1758','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1759','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1760','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1761','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1762','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1763','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1764','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1765','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1766','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1770','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1771','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1772','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1773','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1774','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1775','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1777','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1780','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1782','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1785','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1786','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1787','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1790','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1799','København V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1800','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1801','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1802','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1803','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1804','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1805','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1806','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1807','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1808','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1809','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1810','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1811','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1812','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1813','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1814','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1815','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1816','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1817','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1818','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1819','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1820','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1822','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1823','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1824','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1825','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1826','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1827','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1828','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1829','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1835','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1850','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1851','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1852','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1853','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1854','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1855','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1856','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1857','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1860','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1861','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1862','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1863','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1864','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1865','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1866','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1867','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1868','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1870','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1871','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1872','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1873','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1874','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1875','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1876','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1877','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1878','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1879','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1900','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1901','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1902','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1903','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1904','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1905','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1906','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1908','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1909','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1910','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1911','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1912','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1913','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1914','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1915','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1916','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1917','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1920','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1921','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1922','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1923','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1924','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1925','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1926','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1927','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1928','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1931','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1950','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1951','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1952','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1953','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1954','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1955','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1956','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1957','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1958','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1959','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1960','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1961','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1962','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1963','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1964','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1965','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1966','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1967','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1970','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1971','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1972','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1973','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('1974','Frederiksberg C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2000','Frederiksberg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2100','København Ø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2150','Nordhavn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2200','København N');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2300','København S');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2400','København NV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2450','København SV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2500','Valby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2600','Glostrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2605','Brøndby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2610','Rødovre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2620','Albertslund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2625','Vallensbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2630','Taastrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2635','Ishøj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2640','Hedehusene');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2650','Hvidovre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2660','Brøndby Strand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2665','Vallensbæk Strand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2670','Greve');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2680','Solrød Strand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2690','Karlslunde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2700','Brønshøj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2720','Vanløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2730','Herlev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2740','Skovlunde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2750','Ballerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2760','Måløv');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2765','Smørum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2770','Kastrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2791','Dragør');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2800','Kongens Lyngby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2820','Gentofte');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2830','Virum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2840','Holte');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2850','Nærum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2860','Søborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2870','Dyssegård');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2880','Bagsværd');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2900','Hellerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2920','Charlottenlund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2930','Klampenborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2942','Skodsborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2950','Vedbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2960','Rungsted Kyst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2970','Hørsholm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2980','Kokkedal');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2990','Nivå');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3000','Helsingør');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3050','Humlebæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3060','Espergærde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3070','Snekkersten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3080','Tikøb');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3100','Hornbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3120','Dronningmølle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3140','Ålsgårde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3150','Hellebæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3200','Helsinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3210','Vejby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3220','Tisvildeleje');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3230','Græsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3250','Gilleleje');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3300','Frederiksværk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3310','Ølsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3320','Skævinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3330','Gørløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3360','Liseleje');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3370','Melby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3390','Hundested');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3400','Hillerød');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3450','Allerød');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3460','Birkerød');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3480','Fredensborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3490','Kvistgård');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3500','Værløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3520','Farum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3540','Lynge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3550','Slangerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3600','Frederikssund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3630','Jægerspris');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3650','Ølstykke');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3660','Stenløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3670','Veksø Sjælland');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3700','Rønne');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3720','Aakirkeby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3730','Nexø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3740','Svaneke');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3751','Østermarie');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3760','Gudhjem');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3770','Allinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3782','Klemensker');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3790','Hasle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4000','Roskilde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4030','Tune');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4040','Jyllinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4050','Skibby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4060','Kirke Såby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4070','Kirke Hyllinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4100','Ringsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4129','Ringsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4130','Viby Sjælland');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4140','Borup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4160','Herlufmagle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4171','Glumsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4173','Fjenneslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4174','Jystrup Midtsj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4180','Sorø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4190','Munke Bjergby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4200','Slagelse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4220','Korsør');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4230','Skælskør');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4241','Vemmelev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4242','Boeslunde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4243','Rude');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4250','Fuglebjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4261','Dalmose');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4262','Sandved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4270','Høng');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4281','Gørlev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4291','Ruds Vedby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4293','Dianalund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4295','Stenlille');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4296','Nyrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4300','Holbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4320','Lejre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4330','Hvalsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4340','Tølløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4350','Ugerløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4360','Kirke Eskilstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4370','Store Merløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4390','Vipperød');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4400','Kalundborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4420','Regstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4440','Mørkøv');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4450','Jyderup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4460','Snertinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4470','Svebølle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4480','Store Fuglede');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4490','Jerslev Sjælland');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4500','Nykøbing Sj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4520','Svinninge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4532','Gislinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4534','Hørve');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4540','Fårevejle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4550','Asnæs');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4560','Vig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4571','Grevinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4572','Nørre Asmindrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4573','Højby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4581','Rørvig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4583','Sjællands Odde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4591','Føllenslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4592','Sejerø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4593','Eskebjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4600','Køge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4621','Gadstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4622','Havdrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4623','Lille Skensved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4632','Bjæverskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4640','Faxe');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4652','Hårlev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4653','Karise');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4654','Faxe Ladeplads');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4660','Store Heddinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4671','Strøby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4672','Klippinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4673','Rødvig Stevns');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4681','Herfølge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4682','Tureby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4683','Rønnede');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4684','Holmegaard');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4690','Haslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4700','Næstved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4720','Præstø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4733','Tappernøje');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4735','Mern');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4736','Karrebæksminde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4750','Lundby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4760','Vordingborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4771','Kalvehave');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4772','Langebæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4773','Stensved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4780','Stege');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4791','Borre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4792','Askeby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4793','Bogø By');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4800','Nykøbing F');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4840','Nørre Alslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4850','Stubbekøbing');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4862','Guldborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4863','Eskilstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4871','Horbelev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4872','Idestrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4873','Væggerløse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4874','Gedser');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4880','Nysted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4891','Toreby L');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4892','Kettinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4894','Øster Ulslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4895','Errindlev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4900','Nakskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4912','Harpelunde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4913','Horslunde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4920','Søllested');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4930','Maribo');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4941','Bandholm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4943','Torrig L');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4944','Fejø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4951','Nørreballe');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4952','Stokkemarke');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4953','Vesterborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4960','Holeby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4970','Rødby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4983','Dannemare');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4990','Sakskøbing');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('4992','Midtsjælland USF P');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5000','Odense C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5029','Odense C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5100','Odense C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5200','Odense V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5210','Odense NV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5220','Odense SØ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5230','Odense M');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5240','Odense NØ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5250','Odense SV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5260','Odense S');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5270','Odense N');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5290','Marslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5300','Kerteminde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5320','Agedrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5330','Munkebo');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5350','Rynkeby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5370','Mesinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5380','Dalby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5390','Martofte');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5400','Bogense');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5450','Otterup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5462','Morud');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5463','Harndrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5464','Brenderup Fyn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5466','Asperup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5471','Søndersø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5474','Veflinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5485','Skamby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5491','Blommenslyst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5492','Vissenbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5500','Middelfart');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5540','Ullerslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5550','Langeskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5560','Aarup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5580','Nørre Aaby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5591','Gelsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5592','Ejby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5600','Faaborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5610','Assens');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5620','Glamsbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5631','Ebberup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5642','Millinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5672','Broby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5683','Haarby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5690','Tommerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5700','Svendborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5750','Ringe');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5762','Vester Skerninge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5771','Stenstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5772','Kværndrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5792','Årslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5800','Nyborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5853','Ørbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5854','Gislev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5856','Ryslinge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5863','Ferritslev Fyn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5871','Frørup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5874','Hesselager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5881','Skårup Fyn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5882','Vejstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5883','Oure');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5884','Gudme');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5892','Gudbjerg Sydfyn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5900','Rudkøbing');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5932','Humble');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5935','Bagenkop');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5953','Tranekær');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5960','Marstal');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5970','Ærøskøbing');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('5985','Søby Ærø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6000','Kolding');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6040','Egtved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6051','Almind');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6052','Viuf');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6064','Jordrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6070','Christiansfeld');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6091','Bjert');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6092','Sønder Stenderup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6093','Sjølund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6094','Hejls');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6100','Haderslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6200','Aabenraa');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6230','Rødekro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6240','Løgumkloster');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6261','Bredebro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6270','Tønder');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6280','Højer');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6300','Gråsten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6310','Broager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6320','Egernsund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6330','Padborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6340','Kruså');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6360','Tinglev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6372','Bylderup-Bov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6392','Bolderslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6400','Sønderborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6430','Nordborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6440','Augustenborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6470','Sydals');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6500','Vojens');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6510','Gram');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6520','Toftlund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6534','Agerskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6535','Branderup J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6541','Bevtoft');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6560','Sommersted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6580','Vamdrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6600','Vejen');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6621','Gesten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6622','Bække');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6623','Vorbasse');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6630','Rødding');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6640','Lunderskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6650','Brørup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6660','Lintrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6670','Holsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6682','Hovborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6683','Føvling');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6690','Gørding');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6700','Esbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6701','Esbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6705','Esbjerg Ø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6710','Esbjerg V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6715','Esbjerg N');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6720','Fanø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6731','Tjæreborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6740','Bramming');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6752','Glejbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6753','Agerbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6760','Ribe');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6771','Gredstedbro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6780','Skærbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6792','Rømø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6800','Varde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6818','Årre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6823','Ansager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6830','Nørre Nebel');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6840','Oksbøl');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6851','Janderup Vestj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6852','Billum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6853','Vejers Strand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6854','Henne');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6855','Outrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6857','Blåvand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6862','Tistrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6870','Ølgod');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6880','Tarm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6893','Hemmet');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6900','Skjern');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6920','Videbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6933','Kibæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6940','Lem St');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6950','Ringkøbing');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6960','Hvide Sande');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6971','Spjald');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6973','Ørnhøj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6980','Tim');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('6990','Ulfborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7000','Fredericia');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7007','Fredericia');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7017','Taulov Pakkecenter');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7018','Pakker TLP');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7029','Fredericia');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7080','Børkop');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7100','Vejle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7120','Vejle Øst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7130','Juelsminde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7140','Stouby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7150','Barrit');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7160','Tørring');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7171','Uldum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7173','Vonge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7182','Bredsten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7183','Randbøl');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7184','Vandel');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7190','Billund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7200','Grindsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7250','Hejnsvig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7260','Sønder Omme');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7270','Stakroge');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7280','Sønder Felding');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7300','Jelling');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7321','Gadbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7323','Give');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7330','Brande');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7361','Ejstrupholm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7362','Hampen');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7400','Herning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7429','Herning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7430','Ikast');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7441','Bording');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7442','Engesvang');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7451','Sunds');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7470','Karup J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7480','Vildbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7490','Aulum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7500','Holstebro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7540','Haderup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7550','Sørvad');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7560','Hjerm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7570','Vemb');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7600','Struer');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7620','Lemvig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7650','Bøvlingbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7660','Bækmarksbro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7673','Harboøre');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7680','Thyborøn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7700','Thisted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7730','Hanstholm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7741','Frøstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7742','Vesløs');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7752','Snedsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7755','Bedsted Thy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7760','Hurup Thy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7770','Vestervig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7790','Thyholm');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7800','Skive');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7830','Vinderup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7840','Højslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7850','Stoholm Jyll');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7860','Spøttrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7870','Roslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7884','Fur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7900','Nykøbing M');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7950','Erslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7960','Karby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7970','Redsted M');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7980','Vils');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7990','Øster Assels');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7992','Sydjylland/Fyn USF P');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7993','Sydjylland/Fyn USF B');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7996','Fakturaservice');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7997','Fakturascanning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7998','Statsservice');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('7999','Kommunepost');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8000','Aarhus C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8100','Aarhus C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8200','Aarhus N');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8210','Aarhus V');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8220','Brabrand');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8229','Risskov Ø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8230','Åbyhøj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8240','Risskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8245','Risskov Ø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8250','Egå');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8260','Viby J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8270','Højbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8300','Odder');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8305','Samsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8310','Tranbjerg J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8320','Mårslet');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8330','Beder');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8340','Malling');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8350','Hundslund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8355','Solbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8361','Hasselager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8362','Hørning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8370','Hadsten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8380','Trige');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8381','Tilst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8382','Hinnerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8400','Ebeltoft');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8410','Rønde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8420','Knebel');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8444','Balle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8450','Hammel');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8462','Harlev J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8464','Galten');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8471','Sabro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8472','Sporup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8500','Grenaa');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8520','Lystrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8530','Hjortshøj');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8541','Skødstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8543','Hornslet');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8544','Mørke');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8550','Ryomgård');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8560','Kolind');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8570','Trustrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8581','Nimtofte');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8585','Glesborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8586','Ørum Djurs');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8592','Anholt');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8600','Silkeborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8620','Kjellerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8632','Lemming');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8641','Sorring');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8643','Ans By');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8653','Them');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8654','Bryrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8660','Skanderborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8670','Låsby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8680','Ry');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8700','Horsens');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8721','Daugård');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8722','Hedensted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8723','Løsning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8732','Hovedgård');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8740','Brædstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8751','Gedved');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8752','Østbirk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8762','Flemming');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8763','Rask Mølle');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8765','Klovborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8766','Nørre Snede');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8781','Stenderup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8783','Hornsyld');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8800','Viborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8830','Tjele');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8831','Løgstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8832','Skals');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8840','Rødkærsbro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8850','Bjerringbro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8860','Ulstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8870','Langå');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8881','Thorsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8882','Fårvang');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8883','Gjern');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8900','Randers C');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8920','Randers NV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8930','Randers NØ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8940','Randers SV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8950','Ørsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8960','Randers SØ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8961','Allingåbro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8963','Auning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8970','Havndal');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8981','Spentrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8983','Gjerlev J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('8990','Fårup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9000','Aalborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9029','Aalborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9100','Aalborg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9200','Aalborg SV');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9210','Aalborg SØ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9220','Aalborg Øst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9230','Svenstrup J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9240','Nibe');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9260','Gistrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9270','Klarup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9280','Storvorde');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9293','Kongerslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9300','Sæby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9310','Vodskov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9320','Hjallerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9330','Dronninglund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9340','Asaa');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9352','Dybvad');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9362','Gandrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9370','Hals');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9380','Vestbjerg');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9381','Sulsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9382','Tylstrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9400','Nørresundby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9430','Vadum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9440','Aabybro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9460','Brovst');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9480','Løkken');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9490','Pandrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9492','Blokhus');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9493','Saltum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9500','Hobro');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9510','Arden');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9520','Skørping');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9530','Støvring');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9541','Suldrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9550','Mariager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9560','Hadsund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9574','Bælum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9575','Terndrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9600','Aars');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9610','Nørager');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9620','Aalestrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9631','Gedsted');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9632','Møldrup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9640','Farsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9670','Løgstør');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9681','Ranum');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9690','Fjerritslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9700','Brønderslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9740','Jerslev J');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9750','Østervrå');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9760','Vrå');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9800','Hjørring');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9830','Tårs');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9850','Hirtshals');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9870','Sindal');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9881','Bindslev');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9900','Frederikshavn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9940','Læsø');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9970','Strandby');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9981','Jerup');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9982','Ålbæk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9990','Skagen');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9992','Jylland USF P');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9993','Jylland USF B');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9996','Fakturaservice');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9997','Fakturascanning');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('9998','Borgerservice');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('2412','Santa Claus/Julemanden');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3900','Nuuk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3905','Nuussuaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3910','Kangerlussuaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3911','Sisimiut');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3912','Maniitsoq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3913','Tasiilaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3915','Kulusuk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3919','Alluitsup Paa');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3920','Qaqortoq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3921','Narsaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3922','Nanortalik');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3923','Narsarsuaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3924','Ikerasassuaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3930','Kangilinnguit');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3932','Arsuk');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3940','Paamiut');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3950','Aasiaat');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3951','Qasigiannguit');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3952','Ilulissat');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3953','Qeqertarsuaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3955','Kangaatsiaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3961','Uummannaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3962','Upernavik');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3964','Qaarsut');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3970','Pituffik');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3971','Qaanaaq');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3972','Station Nord');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3980','Ittoqqortoormiit');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3982','Mestersvig');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3984','Danmarkshavn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3985','Constable Pynt');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('3992','Slædepatrulje Sirius');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('100','Tórshavn');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('110','Tórshavn ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('160','Argir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('165','Argir ');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('175','Kirkjubøur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('176','Velbastadur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('177','Sydradalur, Streymoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('178','Nordradalur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('180','Kaldbak');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('185','Kaldbaksbotnur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('186','Sund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('187','Hvitanes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('188','Hoyvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('210','Sandur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('215','Sandur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('220','Skálavík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('230','Húsavík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('235','Dalur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('236','Skarvanes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('240','Skopun');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('260','Skúvoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('270','Nólsoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('280','Hestur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('285','Koltur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('286','Stóra Dimun');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('330','Stykkid');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('335','Leynar');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('336','Skællingur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('340','Kvívík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('350','Vestmanna');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('355','Vestmanna');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('358','Válur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('360','Sandavágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('370','Midvágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('375','Midvágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('380','Sørvágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('385','Vatnsoyrar');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('386','Bøur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('387','Gásadalur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('388','Mykines');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('400','Oyrarbakki');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('405','Oyrarbakki');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('410','Kollafjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('415','Oyrareingir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('416','Signabøur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('420','Hósvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('430','Hvalvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('435','Streymnes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('436','Saksun');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('437','Nesvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('438','Langasandur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('440','Haldarsvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('445','Tjørnuvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('450','Oyri');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('460','Nordskáli');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('465','Svináir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('466','Ljósá');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('470','Eidi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('475','Funningur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('476','Gjógv');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('477','Funningsfjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('478','Elduvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('480','Skáli');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('485','Skálafjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('490','Strendur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('494','Innan Glyvur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('495','Kolbanargjógv');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('496','Morskranes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('497','Selatrad');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('510','Gøta');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('511','Gøtugjógv');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('512','Nordragøta');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('513','Sydrugøta');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('515','Gøta');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('520','Leirvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('530','Fuglafjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('535','Fuglafjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('600','Saltangará');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('610','Saltangará');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('620','Runavík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('625','Glyvrar');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('626','Lambareidi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('627','Lambi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('640','Rituvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('645','Æduvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('650','Toftir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('655','Nes, Eysturoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('656','Saltnes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('660','Søldarfjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('665','Skipanes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('666','Gøtueidi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('690','Oyndarfjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('695','Hellur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('700','Klaksvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('710','Klaksvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('725','Nordoyri');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('726','Ánir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('727','Árnafjørdur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('730','Norddepil');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('735','Depil');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('736','Nordtoftir');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('737','Múli');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('740','Hvannasund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('750','Vidareidi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('765','Svinoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('766','Kirkja');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('767','Hattarvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('780','Kunoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('785','Haraldssund');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('795','Sydradalur, Kalsoy');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('796','Húsar');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('797','Mikladalur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('798','Trøllanes');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('800','Tvøroyri');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('810','Tvøroyri');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('825','Frodba');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('826','Trongisvágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('827','Øravík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('850','Hvalba');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('860','Sandvík');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('870','Fámjin');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('900','Vágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('910','Vágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('925','Nes, Vágur');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('926','Lopra');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('927','Akrar');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('928','Vikarbyrgi');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('950','Porkeri');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('960','Hov');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('970','Sumba');
INSERT INTO CITYINFO (zipCode, cityName) VALUES ('','undefined');